class CredentialsType:
    # Notifiers
    NOTIFIER = 'NOTIFIER'
    NOTIFIER_DEFAULT = 'NOTIFIER_DEFAULT'

    # Uploader
    UPLOADER = 'UPLOADER'
    UPLOADER_DEFAULT = 'UPLOADER_DEFAULT'
    UPLOADER_BUFFERED = 'UPLOADER_BUFFERED'
